---
service: kamal_pg_app_1
image: <DOCKER_USERNAME>/kamal_pg_app_1
servers:
  web:
    hosts:
      - <SERVER_IP_ADDRESS>
    labels:
      traefik.http.routers.gems_directory.entrypoints: websecure
      traefik.http.routers.gems_directory.rule: 'Host(`<DOMAIN_NAME>`) || Host(`<DOMAIN_NAME_WITH_WWW>`)'
      traefik.http.routers.gems_directory.tls.certresolver: letsencrypt
    options:
      network: private
registry:
  username: <DOCKER_USERNAME>
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    HOSTNAME: <DOMAIN_NAME>
    DB_HOST: <SERVER_IP_ADDRESS>
    POSTGRES_USER: kamal_pg_app_1_user
    POSTGRES_DB: kamal_pg_app_1_production
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
volumes:
  - '/storage:/rails/storage'
accessories:
  db:
    image: postgres:16
    host: <SERVER_IP_ADDRESS>
    port: 5432
    env:
      clear:
        DB_HOST: <SERVER_IP_ADDRESS>
        POSTGRES_USER: kamal_pg_app_1_user
        POSTGRES_DB: kamal_pg_app_1_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
traefik:
  options:
    publish:
      - '443:443'
    volume:
      - '/letsencrypt/acme.json:/letsencrypt/acme.json'
    network: 'private'
  args:
    entryPoints.web.address: ':80'
    entryPoints.websecure.address: ':443'
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: '<YOUR_EMAIL_ADDRESS>'
    certificatesResolvers.letsencrypt.acme.storage: '/letsencrypt/acme.json'
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
