# Name of your application. Used to uniquely configure containers.
service: kamal_sqlite_app_2

# Name of the container image.
image: <DOCKER_USERNAME>/kamal_sqlite_app_2

# Deploy to these servers.
servers:
  web:
    hosts:
      - <SERVER_IP_ADDRESS>
    labels:
      traefik.http.routers.dailydevtools.entrypoints: websecure
      traefik.http.routers.dailydevtools.rule: 'Host(`<DOMAIN_NAME>`) || Host(`<DOMAIN_NAME_WITH_WWW>`)'
      traefik.http.routers.dailydevtools.tls.certresolver: letsencrypt
    options:
      network: 'private'
      'add-host': host.docker.internal:host-gateway
# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: <DOCKER_USERNAME>

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD
# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    HOSTNAME: <DOMAIN_NAME>
  secret:
    - RAILS_MASTER_KEY
# Use a different ssh user than root
# ssh:
#   user: app
volumes:
  - '/storage:/rails/storage'
